version: "3.8"

networks:
  go-jwt-authentication:
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: Password!123#
    ports:
      - "5432:5432"
    networks:
      - go-jwt-authentication
